#############################################################################
# Makefile for building: liblibsbg.so.1.0.0
# Generated by qmake (3.0) (Qt 5.6.1)
# Project:  libsbg.pro
# Template: lib
# Command: /usr/bin/qmake-qt5 -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile libsbg.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DLIBSBG_LIBRARY -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I../common_posar -I/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src -I/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtCore -I. -I. -I/usr/lib64/qt5/mkspecs/linux-g++
QMAKE         = /usr/bin/qmake-qt5
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = libsbg1.0.0
DISTDIR = /home/pleroy/Documents/IETR/POSAR-MC/SW/libsbg/.tmp/libsbg1.0.0
LINK          = g++
LFLAGS        = -shared -Wl,-soname,liblibsbg.so.1
LIBS          = $(SUBLIBS) /opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/bin/libsbgECom.a -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = libsbg.cpp \
		qwsbg.cpp \
		sbgconnection.cpp \
		sbgnew.cpp \
		sbgecomlogstatus.cpp \
		sbgecomlogdata.cpp \
		sbgreadfile.cpp moc_qwsbg.cpp \
		moc_sbgconnection.cpp \
		moc_sbgnew.cpp \
		moc_sbgecomlogstatus.cpp \
		moc_sbgecomlogdata.cpp \
		moc_sbgreadfile.cpp
OBJECTS       = libsbg.o \
		qwsbg.o \
		sbgconnection.o \
		sbgnew.o \
		sbgecomlogstatus.o \
		sbgecomlogdata.o \
		sbgreadfile.o \
		moc_qwsbg.o \
		moc_sbgconnection.o \
		moc_sbgnew.o \
		moc_sbgecomlogstatus.o \
		moc_sbgecomlogdata.o \
		moc_sbgreadfile.o
DIST          = /usr/lib64/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib64/qt5/mkspecs/common/unix.conf \
		/usr/lib64/qt5/mkspecs/common/linux.conf \
		/usr/lib64/qt5/mkspecs/common/sanitize.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt5/mkspecs/common/g++-base.conf \
		/usr/lib64/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib64/qt5/mkspecs/qconfig.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_clucene_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webkit_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/lib64/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt5/mkspecs/features/qt_config.prf \
		/usr/lib64/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib64/qt5/mkspecs/features/spec_post.prf \
		/usr/lib64/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt5/mkspecs/features/default_pre.prf \
		/usr/lib64/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib64/qt5/mkspecs/features/default_post.prf \
		/usr/lib64/qt5/mkspecs/features/qml_debug.prf \
		/usr/lib64/qt5/mkspecs/features/warn_on.prf \
		/usr/lib64/qt5/mkspecs/features/qt.prf \
		/usr/lib64/qt5/mkspecs/features/resources.prf \
		/usr/lib64/qt5/mkspecs/features/moc.prf \
		/usr/lib64/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib64/qt5/mkspecs/features/uic.prf \
		/usr/lib64/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt5/mkspecs/features/file_copies.prf \
		/usr/lib64/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib64/qt5/mkspecs/features/exceptions.prf \
		/usr/lib64/qt5/mkspecs/features/yacc.prf \
		/usr/lib64/qt5/mkspecs/features/lex.prf \
		libsbg.pro libsbg.h \
		qwsbg.h \
		libsbg_global.h \
		sbgconnection.h \
		sbgnew.h \
		sbgecomlogstatus.h \
		sbgecomlogdata.h \
		sbgreadfile.h libsbg.cpp \
		qwsbg.cpp \
		sbgconnection.cpp \
		sbgnew.cpp \
		sbgecomlogstatus.cpp \
		sbgecomlogdata.cpp \
		sbgreadfile.cpp
QMAKE_TARGET  = libsbg
DESTDIR       = 
TARGET        = liblibsbg.so.1.0.0
TARGETA       = liblibsbg.a
TARGET0       = liblibsbg.so
TARGETD       = liblibsbg.so.1.0.0
TARGET1       = liblibsbg.so.1
TARGET2       = liblibsbg.so.1.0


first: all
####### Build rules

$(TARGET): ui_qwsbg.h ui_sbgconnection.h ui_sbgecomlogstatus.h ui_sbgecomlogdata.h ui_sbgreadfile.h $(OBJECTS) $(SUBLIBS) $(OBJCOMP)  
	-$(DEL_FILE) $(TARGET) $(TARGET0) $(TARGET1) $(TARGET2)
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(LIBS) $(OBJCOMP)
	-ln -s $(TARGET) $(TARGET0)
	-ln -s $(TARGET) $(TARGET1)
	-ln -s $(TARGET) $(TARGET2)



staticlib: $(TARGETA)

$(TARGETA): ui_qwsbg.h ui_sbgconnection.h ui_sbgecomlogstatus.h ui_sbgecomlogdata.h ui_sbgreadfile.h $(OBJECTS) $(OBJCOMP) 
	-$(DEL_FILE) $(TARGETA) 
	$(AR) $(TARGETA) $(OBJECTS)

Makefile: libsbg.pro /usr/lib64/qt5/mkspecs/linux-g++/qmake.conf /usr/lib64/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib64/qt5/mkspecs/common/unix.conf \
		/usr/lib64/qt5/mkspecs/common/linux.conf \
		/usr/lib64/qt5/mkspecs/common/sanitize.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt5/mkspecs/common/g++-base.conf \
		/usr/lib64/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib64/qt5/mkspecs/qconfig.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_clucene_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webkit_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/lib64/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt5/mkspecs/features/qt_config.prf \
		/usr/lib64/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib64/qt5/mkspecs/features/spec_post.prf \
		/usr/lib64/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt5/mkspecs/features/default_pre.prf \
		/usr/lib64/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib64/qt5/mkspecs/features/default_post.prf \
		/usr/lib64/qt5/mkspecs/features/qml_debug.prf \
		/usr/lib64/qt5/mkspecs/features/warn_on.prf \
		/usr/lib64/qt5/mkspecs/features/qt.prf \
		/usr/lib64/qt5/mkspecs/features/resources.prf \
		/usr/lib64/qt5/mkspecs/features/moc.prf \
		/usr/lib64/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib64/qt5/mkspecs/features/uic.prf \
		/usr/lib64/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt5/mkspecs/features/file_copies.prf \
		/usr/lib64/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib64/qt5/mkspecs/features/exceptions.prf \
		/usr/lib64/qt5/mkspecs/features/yacc.prf \
		/usr/lib64/qt5/mkspecs/features/lex.prf \
		libsbg.pro \
		/usr/lib64/libQt5Widgets.prl \
		/usr/lib64/libQt5Gui.prl \
		/usr/lib64/libQt5Core.prl
	$(QMAKE) -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile libsbg.pro
/usr/lib64/qt5/mkspecs/features/spec_pre.prf:
/usr/lib64/qt5/mkspecs/common/unix.conf:
/usr/lib64/qt5/mkspecs/common/linux.conf:
/usr/lib64/qt5/mkspecs/common/sanitize.conf:
/usr/lib64/qt5/mkspecs/common/gcc-base.conf:
/usr/lib64/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib64/qt5/mkspecs/common/g++-base.conf:
/usr/lib64/qt5/mkspecs/common/g++-unix.conf:
/usr/lib64/qt5/mkspecs/qconfig.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_clucene_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_designer.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_designer_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_help.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_help_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_multimedia.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_qml_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_quick_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_svg.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_svg_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_uitools.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webkit.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webkit_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/usr/lib64/qt5/mkspecs/features/qt_functions.prf:
/usr/lib64/qt5/mkspecs/features/qt_config.prf:
/usr/lib64/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib64/qt5/mkspecs/features/spec_post.prf:
/usr/lib64/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib64/qt5/mkspecs/features/default_pre.prf:
/usr/lib64/qt5/mkspecs/features/resolve_config.prf:
/usr/lib64/qt5/mkspecs/features/default_post.prf:
/usr/lib64/qt5/mkspecs/features/qml_debug.prf:
/usr/lib64/qt5/mkspecs/features/warn_on.prf:
/usr/lib64/qt5/mkspecs/features/qt.prf:
/usr/lib64/qt5/mkspecs/features/resources.prf:
/usr/lib64/qt5/mkspecs/features/moc.prf:
/usr/lib64/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib64/qt5/mkspecs/features/uic.prf:
/usr/lib64/qt5/mkspecs/features/unix/thread.prf:
/usr/lib64/qt5/mkspecs/features/file_copies.prf:
/usr/lib64/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib64/qt5/mkspecs/features/exceptions.prf:
/usr/lib64/qt5/mkspecs/features/yacc.prf:
/usr/lib64/qt5/mkspecs/features/lex.prf:
libsbg.pro:
/usr/lib64/libQt5Widgets.prl:
/usr/lib64/libQt5Gui.prl:
/usr/lib64/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile libsbg.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib64/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents libsbg.h qwsbg.h libsbg_global.h sbgconnection.h sbgnew.h sbgecomlogstatus.h sbgecomlogdata.h sbgreadfile.h $(DISTDIR)/
	$(COPY_FILE) --parents libsbg.cpp qwsbg.cpp sbgconnection.cpp sbgnew.cpp sbgecomlogstatus.cpp sbgecomlogdata.cpp sbgreadfile.cpp $(DISTDIR)/
	$(COPY_FILE) --parents qwsbg.ui sbgconnection.ui sbgecomlogstatus.ui sbgecomlogdata.ui sbgreadfile.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) $(TARGET0) $(TARGET1) $(TARGET2) $(TARGETA)
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib64/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -g -Wall -W -dM -E -o moc_predefs.h /usr/lib64/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_qwsbg.cpp moc_sbgconnection.cpp moc_sbgnew.cpp moc_sbgecomlogstatus.cpp moc_sbgecomlogdata.cpp moc_sbgreadfile.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_qwsbg.cpp moc_sbgconnection.cpp moc_sbgnew.cpp moc_sbgecomlogstatus.cpp moc_sbgecomlogdata.cpp moc_sbgreadfile.cpp
moc_qwsbg.cpp: /opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/sbgECom.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/sbgCommon.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/platform/sbgPlatform.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/sbgTypes.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/sbgErrorCodes.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/sbgDefines.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/sbgDebug.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/platform/sbgConfig.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/version/sbgVersion.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/sbgEComIds.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/protocol/sbgEComProtocol.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/interfaces/sbgInterface.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/streamBuffer/sbgStreamBuffer.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/streamBuffer/sbgStreamBufferLE.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/streamBuffer/sbgStreamBufferCommon.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/streamBuffer/sbgStreamBufferBE.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogs.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogDebug.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogDvl.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogEkf.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogEvent.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogGps.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogImu.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogMag.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogOdometer.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogPressure.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogShipMotion.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogStatus.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogUsbl.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogUtc.h \
		libsbg_global.h \
		qwsbg.h \
		moc_predefs.h
	/usr/lib64/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/home/pleroy/Documents/IETR/POSAR-MC/SW/libsbg -I/home/pleroy/Documents/IETR/POSAR-MC/SW/common_posar -I'/opt/SBG/InertialSDK_Unix_v3.5.0/Software Development/sbgECom/src' -I'/opt/SBG/InertialSDK_Unix_v3.5.0/Software Development/sbgECom/common' -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/include/c++/6.1.1 -I/usr/include/c++/6.1.1/x86_64-redhat-linux -I/usr/include/c++/6.1.1/backward -I/usr/lib/gcc/x86_64-redhat-linux/6.1.1/include -I/usr/local/include -I/usr/include qwsbg.h -o moc_qwsbg.cpp

moc_sbgconnection.cpp: libsbg_global.h \
		sbgnew.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/sbgEComLib.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/sbgCommon.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/platform/sbgPlatform.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/sbgTypes.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/sbgErrorCodes.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/sbgDefines.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/sbgDebug.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/platform/sbgConfig.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/version/sbgVersion.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/crc/sbgCrc.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/interfaces/sbgInterface.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/interfaces/sbgInterfaceUdp.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/interfaces/sbgInterfaceSerial.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/interfaces/sbgInterfaceFile.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/splitBuffer/sbgSplitBuffer.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/streamBuffer/sbgStreamBuffer.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/streamBuffer/sbgStreamBufferLE.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/streamBuffer/sbgStreamBufferCommon.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/streamBuffer/sbgStreamBufferBE.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/network/sbgNetwork.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/swap/sbgSwap.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/sbgECanId.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/sbgEComIds.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/commands/sbgEComCmd.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/commands/sbgEComCmdAdvanced.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/commands/sbgEComCmdCommon.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/sbgECom.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/protocol/sbgEComProtocol.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogs.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogDebug.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogDvl.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogEkf.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogEvent.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogGps.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogImu.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogMag.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogOdometer.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogPressure.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogShipMotion.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogStatus.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogUsbl.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogUtc.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/commands/sbgEComCmdEvent.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/commands/sbgEComCmdFeatures.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/commands/sbgEComCmdGnss.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/commands/sbgEComCmdInfo.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/commands/sbgEComCmdInterface.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/commands/sbgEComCmdLicense.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/commands/sbgEComCmdMag.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/commands/sbgEComCmdOdo.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/commands/sbgEComCmdOutput.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/commands/sbgEComCmdSensor.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/commands/sbgEComCmdSettings.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/sbgEComVersion.h \
		sbgconnection.h \
		moc_predefs.h
	/usr/lib64/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/home/pleroy/Documents/IETR/POSAR-MC/SW/libsbg -I/home/pleroy/Documents/IETR/POSAR-MC/SW/common_posar -I'/opt/SBG/InertialSDK_Unix_v3.5.0/Software Development/sbgECom/src' -I'/opt/SBG/InertialSDK_Unix_v3.5.0/Software Development/sbgECom/common' -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/include/c++/6.1.1 -I/usr/include/c++/6.1.1/x86_64-redhat-linux -I/usr/include/c++/6.1.1/backward -I/usr/lib/gcc/x86_64-redhat-linux/6.1.1/include -I/usr/local/include -I/usr/include sbgconnection.h -o moc_sbgconnection.cpp

moc_sbgnew.cpp: libsbg_global.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/sbgEComLib.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/sbgCommon.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/platform/sbgPlatform.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/sbgTypes.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/sbgErrorCodes.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/sbgDefines.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/sbgDebug.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/platform/sbgConfig.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/version/sbgVersion.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/crc/sbgCrc.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/interfaces/sbgInterface.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/interfaces/sbgInterfaceUdp.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/interfaces/sbgInterfaceSerial.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/interfaces/sbgInterfaceFile.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/splitBuffer/sbgSplitBuffer.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/streamBuffer/sbgStreamBuffer.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/streamBuffer/sbgStreamBufferLE.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/streamBuffer/sbgStreamBufferCommon.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/streamBuffer/sbgStreamBufferBE.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/network/sbgNetwork.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/swap/sbgSwap.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/sbgECanId.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/sbgEComIds.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/commands/sbgEComCmd.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/commands/sbgEComCmdAdvanced.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/commands/sbgEComCmdCommon.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/sbgECom.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/protocol/sbgEComProtocol.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogs.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogDebug.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogDvl.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogEkf.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogEvent.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogGps.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogImu.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogMag.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogOdometer.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogPressure.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogShipMotion.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogStatus.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogUsbl.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogUtc.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/commands/sbgEComCmdEvent.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/commands/sbgEComCmdFeatures.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/commands/sbgEComCmdGnss.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/commands/sbgEComCmdInfo.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/commands/sbgEComCmdInterface.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/commands/sbgEComCmdLicense.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/commands/sbgEComCmdMag.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/commands/sbgEComCmdOdo.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/commands/sbgEComCmdOutput.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/commands/sbgEComCmdSensor.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/commands/sbgEComCmdSettings.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/sbgEComVersion.h \
		sbgnew.h \
		moc_predefs.h
	/usr/lib64/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/home/pleroy/Documents/IETR/POSAR-MC/SW/libsbg -I/home/pleroy/Documents/IETR/POSAR-MC/SW/common_posar -I'/opt/SBG/InertialSDK_Unix_v3.5.0/Software Development/sbgECom/src' -I'/opt/SBG/InertialSDK_Unix_v3.5.0/Software Development/sbgECom/common' -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/include/c++/6.1.1 -I/usr/include/c++/6.1.1/x86_64-redhat-linux -I/usr/include/c++/6.1.1/backward -I/usr/lib/gcc/x86_64-redhat-linux/6.1.1/include -I/usr/local/include -I/usr/include sbgnew.h -o moc_sbgnew.cpp

moc_sbgecomlogstatus.cpp: libsbg_global.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogs.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/sbgCommon.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/platform/sbgPlatform.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/sbgTypes.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/sbgErrorCodes.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/sbgDefines.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/sbgDebug.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/platform/sbgConfig.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/version/sbgVersion.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/sbgEComIds.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogDebug.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/streamBuffer/sbgStreamBuffer.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/streamBuffer/sbgStreamBufferLE.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/streamBuffer/sbgStreamBufferCommon.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/streamBuffer/sbgStreamBufferBE.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogDvl.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogEkf.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogEvent.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogGps.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogImu.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogMag.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogOdometer.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogPressure.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogShipMotion.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogStatus.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogUsbl.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogUtc.h \
		sbgecomlogstatus.h \
		moc_predefs.h
	/usr/lib64/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/home/pleroy/Documents/IETR/POSAR-MC/SW/libsbg -I/home/pleroy/Documents/IETR/POSAR-MC/SW/common_posar -I'/opt/SBG/InertialSDK_Unix_v3.5.0/Software Development/sbgECom/src' -I'/opt/SBG/InertialSDK_Unix_v3.5.0/Software Development/sbgECom/common' -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/include/c++/6.1.1 -I/usr/include/c++/6.1.1/x86_64-redhat-linux -I/usr/include/c++/6.1.1/backward -I/usr/lib/gcc/x86_64-redhat-linux/6.1.1/include -I/usr/local/include -I/usr/include sbgecomlogstatus.h -o moc_sbgecomlogstatus.cpp

moc_sbgecomlogdata.cpp: /opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogs.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/sbgCommon.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/platform/sbgPlatform.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/sbgTypes.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/sbgErrorCodes.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/sbgDefines.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/sbgDebug.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/platform/sbgConfig.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/version/sbgVersion.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/sbgEComIds.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogDebug.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/streamBuffer/sbgStreamBuffer.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/streamBuffer/sbgStreamBufferLE.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/streamBuffer/sbgStreamBufferCommon.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/streamBuffer/sbgStreamBufferBE.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogDvl.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogEkf.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogEvent.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogGps.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogImu.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogMag.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogOdometer.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogPressure.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogShipMotion.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogStatus.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogUsbl.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogUtc.h \
		sbgecomlogdata.h \
		moc_predefs.h
	/usr/lib64/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/home/pleroy/Documents/IETR/POSAR-MC/SW/libsbg -I/home/pleroy/Documents/IETR/POSAR-MC/SW/common_posar -I'/opt/SBG/InertialSDK_Unix_v3.5.0/Software Development/sbgECom/src' -I'/opt/SBG/InertialSDK_Unix_v3.5.0/Software Development/sbgECom/common' -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/include/c++/6.1.1 -I/usr/include/c++/6.1.1/x86_64-redhat-linux -I/usr/include/c++/6.1.1/backward -I/usr/lib/gcc/x86_64-redhat-linux/6.1.1/include -I/usr/local/include -I/usr/include sbgecomlogdata.h -o moc_sbgecomlogdata.cpp

moc_sbgreadfile.cpp: /opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/sbgEComLib.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/sbgCommon.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/platform/sbgPlatform.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/sbgTypes.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/sbgErrorCodes.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/sbgDefines.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/sbgDebug.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/platform/sbgConfig.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/version/sbgVersion.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/crc/sbgCrc.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/interfaces/sbgInterface.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/interfaces/sbgInterfaceUdp.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/interfaces/sbgInterfaceSerial.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/interfaces/sbgInterfaceFile.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/splitBuffer/sbgSplitBuffer.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/streamBuffer/sbgStreamBuffer.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/streamBuffer/sbgStreamBufferLE.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/streamBuffer/sbgStreamBufferCommon.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/streamBuffer/sbgStreamBufferBE.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/network/sbgNetwork.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/swap/sbgSwap.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/sbgECanId.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/sbgEComIds.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/commands/sbgEComCmd.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/commands/sbgEComCmdAdvanced.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/commands/sbgEComCmdCommon.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/sbgECom.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/protocol/sbgEComProtocol.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogs.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogDebug.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogDvl.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogEkf.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogEvent.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogGps.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogImu.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogMag.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogOdometer.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogPressure.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogShipMotion.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogStatus.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogUsbl.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogUtc.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/commands/sbgEComCmdEvent.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/commands/sbgEComCmdFeatures.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/commands/sbgEComCmdGnss.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/commands/sbgEComCmdInfo.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/commands/sbgEComCmdInterface.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/commands/sbgEComCmdLicense.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/commands/sbgEComCmdMag.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/commands/sbgEComCmdOdo.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/commands/sbgEComCmdOutput.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/commands/sbgEComCmdSensor.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/commands/sbgEComCmdSettings.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/sbgEComVersion.h \
		libsbg_global.h \
		../common_posar/common_tctmserver.h \
		sbgreadfile.h \
		moc_predefs.h
	/usr/lib64/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/home/pleroy/Documents/IETR/POSAR-MC/SW/libsbg -I/home/pleroy/Documents/IETR/POSAR-MC/SW/common_posar -I'/opt/SBG/InertialSDK_Unix_v3.5.0/Software Development/sbgECom/src' -I'/opt/SBG/InertialSDK_Unix_v3.5.0/Software Development/sbgECom/common' -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/include/c++/6.1.1 -I/usr/include/c++/6.1.1/x86_64-redhat-linux -I/usr/include/c++/6.1.1/backward -I/usr/lib/gcc/x86_64-redhat-linux/6.1.1/include -I/usr/local/include -I/usr/include sbgreadfile.h -o moc_sbgreadfile.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_qwsbg.h ui_sbgconnection.h ui_sbgecomlogstatus.h ui_sbgecomlogdata.h ui_sbgreadfile.h
compiler_uic_clean:
	-$(DEL_FILE) ui_qwsbg.h ui_sbgconnection.h ui_sbgecomlogstatus.h ui_sbgecomlogdata.h ui_sbgreadfile.h
ui_qwsbg.h: qwsbg.ui \
		sbgconnection.h \
		sbgecomlogstatus.h \
		sbgecomlogdata.h \
		libsbg_global.h \
		sbgnew.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/sbgEComLib.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/sbgCommon.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/platform/sbgPlatform.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/sbgTypes.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/sbgErrorCodes.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/sbgDefines.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/sbgDebug.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/platform/sbgConfig.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/version/sbgVersion.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/crc/sbgCrc.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/interfaces/sbgInterface.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/interfaces/sbgInterfaceUdp.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/interfaces/sbgInterfaceSerial.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/interfaces/sbgInterfaceFile.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/splitBuffer/sbgSplitBuffer.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/streamBuffer/sbgStreamBuffer.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/streamBuffer/sbgStreamBufferLE.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/streamBuffer/sbgStreamBufferCommon.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/streamBuffer/sbgStreamBufferBE.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/network/sbgNetwork.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/swap/sbgSwap.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/sbgECanId.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/sbgEComIds.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/commands/sbgEComCmd.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/commands/sbgEComCmdAdvanced.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/commands/sbgEComCmdCommon.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/sbgECom.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/protocol/sbgEComProtocol.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogs.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogDebug.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogDvl.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogEkf.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogEvent.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogGps.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogImu.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogMag.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogOdometer.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogPressure.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogShipMotion.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogStatus.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogUsbl.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogUtc.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/commands/sbgEComCmdEvent.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/commands/sbgEComCmdFeatures.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/commands/sbgEComCmdGnss.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/commands/sbgEComCmdInfo.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/commands/sbgEComCmdInterface.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/commands/sbgEComCmdLicense.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/commands/sbgEComCmdMag.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/commands/sbgEComCmdOdo.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/commands/sbgEComCmdOutput.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/commands/sbgEComCmdSensor.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/commands/sbgEComCmdSettings.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/sbgEComVersion.h \
		libsbg_global.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogs.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/sbgCommon.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/platform/sbgPlatform.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/sbgTypes.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/sbgErrorCodes.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/sbgDefines.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/sbgDebug.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/platform/sbgConfig.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/version/sbgVersion.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/sbgEComIds.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogDebug.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/streamBuffer/sbgStreamBuffer.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/streamBuffer/sbgStreamBufferLE.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/streamBuffer/sbgStreamBufferCommon.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/streamBuffer/sbgStreamBufferBE.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogDvl.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogEkf.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogEvent.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogGps.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogImu.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogMag.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogOdometer.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogPressure.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogShipMotion.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogStatus.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogUsbl.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogUtc.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogs.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/sbgCommon.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/platform/sbgPlatform.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/sbgTypes.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/sbgErrorCodes.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/sbgDefines.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/sbgDebug.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/platform/sbgConfig.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/version/sbgVersion.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/sbgEComIds.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogDebug.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/streamBuffer/sbgStreamBuffer.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/streamBuffer/sbgStreamBufferLE.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/streamBuffer/sbgStreamBufferCommon.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/streamBuffer/sbgStreamBufferBE.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogDvl.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogEkf.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogEvent.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogGps.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogImu.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogMag.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogOdometer.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogPressure.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogShipMotion.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogStatus.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogUsbl.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogUtc.h
	/usr/lib64/qt5/bin/uic qwsbg.ui -o ui_qwsbg.h

ui_sbgconnection.h: sbgconnection.ui
	/usr/lib64/qt5/bin/uic sbgconnection.ui -o ui_sbgconnection.h

ui_sbgecomlogstatus.h: sbgecomlogstatus.ui
	/usr/lib64/qt5/bin/uic sbgecomlogstatus.ui -o ui_sbgecomlogstatus.h

ui_sbgecomlogdata.h: sbgecomlogdata.ui
	/usr/lib64/qt5/bin/uic sbgecomlogdata.ui -o ui_sbgecomlogdata.h

ui_sbgreadfile.h: sbgreadfile.ui
	/usr/lib64/qt5/bin/uic sbgreadfile.ui -o ui_sbgreadfile.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

libsbg.o: libsbg.cpp libsbg.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o libsbg.o libsbg.cpp

qwsbg.o: qwsbg.cpp qwsbg.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/sbgECom.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/sbgCommon.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/platform/sbgPlatform.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/sbgTypes.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/sbgErrorCodes.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/sbgDefines.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/sbgDebug.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/platform/sbgConfig.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/version/sbgVersion.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/sbgEComIds.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/protocol/sbgEComProtocol.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/interfaces/sbgInterface.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/streamBuffer/sbgStreamBuffer.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/streamBuffer/sbgStreamBufferLE.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/streamBuffer/sbgStreamBufferCommon.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/streamBuffer/sbgStreamBufferBE.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogs.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogDebug.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogDvl.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogEkf.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogEvent.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogGps.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogImu.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogMag.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogOdometer.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogPressure.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogShipMotion.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogStatus.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogUsbl.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogUtc.h \
		libsbg_global.h \
		ui_qwsbg.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qwsbg.o qwsbg.cpp

sbgconnection.o: sbgconnection.cpp sbgconnection.h \
		libsbg_global.h \
		sbgnew.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/sbgEComLib.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/sbgCommon.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/platform/sbgPlatform.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/sbgTypes.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/sbgErrorCodes.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/sbgDefines.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/sbgDebug.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/platform/sbgConfig.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/version/sbgVersion.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/crc/sbgCrc.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/interfaces/sbgInterface.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/interfaces/sbgInterfaceUdp.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/interfaces/sbgInterfaceSerial.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/interfaces/sbgInterfaceFile.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/splitBuffer/sbgSplitBuffer.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/streamBuffer/sbgStreamBuffer.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/streamBuffer/sbgStreamBufferLE.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/streamBuffer/sbgStreamBufferCommon.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/streamBuffer/sbgStreamBufferBE.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/network/sbgNetwork.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/swap/sbgSwap.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/sbgECanId.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/sbgEComIds.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/commands/sbgEComCmd.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/commands/sbgEComCmdAdvanced.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/commands/sbgEComCmdCommon.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/sbgECom.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/protocol/sbgEComProtocol.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogs.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogDebug.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogDvl.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogEkf.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogEvent.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogGps.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogImu.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogMag.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogOdometer.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogPressure.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogShipMotion.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogStatus.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogUsbl.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogUtc.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/commands/sbgEComCmdEvent.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/commands/sbgEComCmdFeatures.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/commands/sbgEComCmdGnss.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/commands/sbgEComCmdInfo.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/commands/sbgEComCmdInterface.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/commands/sbgEComCmdLicense.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/commands/sbgEComCmdMag.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/commands/sbgEComCmdOdo.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/commands/sbgEComCmdOutput.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/commands/sbgEComCmdSensor.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/commands/sbgEComCmdSettings.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/sbgEComVersion.h \
		ui_sbgconnection.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sbgconnection.o sbgconnection.cpp

sbgnew.o: sbgnew.cpp sbgnew.h \
		libsbg_global.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/sbgEComLib.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/sbgCommon.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/platform/sbgPlatform.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/sbgTypes.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/sbgErrorCodes.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/sbgDefines.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/sbgDebug.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/platform/sbgConfig.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/version/sbgVersion.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/crc/sbgCrc.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/interfaces/sbgInterface.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/interfaces/sbgInterfaceUdp.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/interfaces/sbgInterfaceSerial.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/interfaces/sbgInterfaceFile.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/splitBuffer/sbgSplitBuffer.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/streamBuffer/sbgStreamBuffer.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/streamBuffer/sbgStreamBufferLE.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/streamBuffer/sbgStreamBufferCommon.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/streamBuffer/sbgStreamBufferBE.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/network/sbgNetwork.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/swap/sbgSwap.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/sbgECanId.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/sbgEComIds.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/commands/sbgEComCmd.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/commands/sbgEComCmdAdvanced.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/commands/sbgEComCmdCommon.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/sbgECom.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/protocol/sbgEComProtocol.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogs.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogDebug.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogDvl.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogEkf.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogEvent.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogGps.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogImu.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogMag.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogOdometer.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogPressure.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogShipMotion.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogStatus.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogUsbl.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogUtc.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/commands/sbgEComCmdEvent.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/commands/sbgEComCmdFeatures.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/commands/sbgEComCmdGnss.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/commands/sbgEComCmdInfo.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/commands/sbgEComCmdInterface.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/commands/sbgEComCmdLicense.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/commands/sbgEComCmdMag.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/commands/sbgEComCmdOdo.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/commands/sbgEComCmdOutput.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/commands/sbgEComCmdSensor.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/commands/sbgEComCmdSettings.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/sbgEComVersion.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sbgnew.o sbgnew.cpp

sbgecomlogstatus.o: sbgecomlogstatus.cpp sbgecomlogstatus.h \
		libsbg_global.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogs.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/sbgCommon.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/platform/sbgPlatform.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/sbgTypes.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/sbgErrorCodes.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/sbgDefines.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/sbgDebug.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/platform/sbgConfig.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/version/sbgVersion.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/sbgEComIds.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogDebug.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/streamBuffer/sbgStreamBuffer.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/streamBuffer/sbgStreamBufferLE.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/streamBuffer/sbgStreamBufferCommon.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/streamBuffer/sbgStreamBufferBE.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogDvl.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogEkf.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogEvent.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogGps.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogImu.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogMag.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogOdometer.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogPressure.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogShipMotion.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogStatus.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogUsbl.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogUtc.h \
		ui_sbgecomlogstatus.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sbgecomlogstatus.o sbgecomlogstatus.cpp

sbgecomlogdata.o: sbgecomlogdata.cpp sbgecomlogdata.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogs.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/sbgCommon.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/platform/sbgPlatform.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/sbgTypes.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/sbgErrorCodes.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/sbgDefines.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/sbgDebug.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/platform/sbgConfig.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/version/sbgVersion.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/sbgEComIds.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogDebug.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/streamBuffer/sbgStreamBuffer.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/streamBuffer/sbgStreamBufferLE.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/streamBuffer/sbgStreamBufferCommon.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/streamBuffer/sbgStreamBufferBE.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogDvl.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogEkf.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogEvent.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogGps.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogImu.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogMag.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogOdometer.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogPressure.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogShipMotion.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogStatus.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogUsbl.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogUtc.h \
		ui_sbgecomlogdata.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sbgecomlogdata.o sbgecomlogdata.cpp

sbgreadfile.o: sbgreadfile.cpp sbgreadfile.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/sbgEComLib.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/sbgCommon.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/platform/sbgPlatform.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/sbgTypes.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/sbgErrorCodes.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/sbgDefines.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/sbgDebug.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/platform/sbgConfig.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/version/sbgVersion.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/crc/sbgCrc.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/interfaces/sbgInterface.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/interfaces/sbgInterfaceUdp.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/interfaces/sbgInterfaceSerial.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/interfaces/sbgInterfaceFile.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/splitBuffer/sbgSplitBuffer.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/streamBuffer/sbgStreamBuffer.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/streamBuffer/sbgStreamBufferLE.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/streamBuffer/sbgStreamBufferCommon.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/streamBuffer/sbgStreamBufferBE.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/network/sbgNetwork.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/common/swap/sbgSwap.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/sbgECanId.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/sbgEComIds.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/commands/sbgEComCmd.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/commands/sbgEComCmdAdvanced.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/commands/sbgEComCmdCommon.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/sbgECom.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/protocol/sbgEComProtocol.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogs.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogDebug.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogDvl.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogEkf.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogEvent.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogGps.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogImu.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogMag.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogOdometer.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogPressure.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogShipMotion.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogStatus.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogUsbl.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/binaryLogs/sbgEComBinaryLogUtc.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/commands/sbgEComCmdEvent.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/commands/sbgEComCmdFeatures.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/commands/sbgEComCmdGnss.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/commands/sbgEComCmdInfo.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/commands/sbgEComCmdInterface.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/commands/sbgEComCmdLicense.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/commands/sbgEComCmdMag.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/commands/sbgEComCmdOdo.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/commands/sbgEComCmdOutput.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/commands/sbgEComCmdSensor.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/commands/sbgEComCmdSettings.h \
		/opt/SBG/InertialSDK_Unix_v3.5.0/Software\ Development/sbgECom/src/sbgEComVersion.h \
		libsbg_global.h \
		../common_posar/common_tctmserver.h \
		ui_sbgreadfile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sbgreadfile.o sbgreadfile.cpp

moc_qwsbg.o: moc_qwsbg.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qwsbg.o moc_qwsbg.cpp

moc_sbgconnection.o: moc_sbgconnection.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_sbgconnection.o moc_sbgconnection.cpp

moc_sbgnew.o: moc_sbgnew.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_sbgnew.o moc_sbgnew.cpp

moc_sbgecomlogstatus.o: moc_sbgecomlogstatus.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_sbgecomlogstatus.o moc_sbgecomlogstatus.cpp

moc_sbgecomlogdata.o: moc_sbgecomlogdata.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_sbgecomlogdata.o moc_sbgecomlogdata.cpp

moc_sbgreadfile.o: moc_sbgreadfile.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_sbgreadfile.o moc_sbgreadfile.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/usr/lib || mkdir -p $(INSTALL_ROOT)/usr/lib
	-$(INSTALL_PROGRAM) $(TARGET) $(INSTALL_ROOT)/usr/lib/$(TARGET)
	-$(SYMLINK) $(TARGET) $(INSTALL_ROOT)/usr/lib/$(TARGET0)
	-$(SYMLINK) $(TARGET) $(INSTALL_ROOT)/usr/lib/$(TARGET1)
	-$(SYMLINK) $(TARGET) $(INSTALL_ROOT)/usr/lib/$(TARGET2)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/usr/lib/$(TARGET) 
	 -$(DEL_FILE) $(INSTALL_ROOT)/usr/lib/$(TARGET0) 
	 -$(DEL_FILE) $(INSTALL_ROOT)/usr/lib/$(TARGET1) 
	 -$(DEL_FILE) $(INSTALL_ROOT)/usr/lib/$(TARGET2)
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/lib/ 


install_headersDataFiles: first FORCE
	@test -d $(INSTALL_ROOT)/usr/include/qt5/ietr/ || mkdir -p $(INSTALL_ROOT)/usr/include/qt5/ietr/
	-$(INSTALL_FILE) /home/pleroy/Documents/IETR/POSAR-MC/SW/libsbg/libsbg.h $(INSTALL_ROOT)/usr/include/qt5/ietr/
	-$(INSTALL_FILE) /home/pleroy/Documents/IETR/POSAR-MC/SW/libsbg/libsbg_global.h $(INSTALL_ROOT)/usr/include/qt5/ietr/
	-$(INSTALL_FILE) /home/pleroy/Documents/IETR/POSAR-MC/SW/libsbg/qwsbg.h $(INSTALL_ROOT)/usr/include/qt5/ietr/
	-$(INSTALL_FILE) /home/pleroy/Documents/IETR/POSAR-MC/SW/libsbg/sbgconnection.h $(INSTALL_ROOT)/usr/include/qt5/ietr/
	-$(INSTALL_FILE) /home/pleroy/Documents/IETR/POSAR-MC/SW/libsbg/sbgecomlogdata.h $(INSTALL_ROOT)/usr/include/qt5/ietr/
	-$(INSTALL_FILE) /home/pleroy/Documents/IETR/POSAR-MC/SW/libsbg/sbgecomlogstatus.h $(INSTALL_ROOT)/usr/include/qt5/ietr/
	-$(INSTALL_FILE) /home/pleroy/Documents/IETR/POSAR-MC/SW/libsbg/sbgnew.h $(INSTALL_ROOT)/usr/include/qt5/ietr/
	-$(INSTALL_FILE) /home/pleroy/Documents/IETR/POSAR-MC/SW/libsbg/sbgreadfile.h $(INSTALL_ROOT)/usr/include/qt5/ietr/
	-$(INSTALL_FILE) /home/pleroy/Documents/IETR/POSAR-MC/SW/libsbg/ui_newsbg.h $(INSTALL_ROOT)/usr/include/qt5/ietr/
	-$(INSTALL_FILE) /home/pleroy/Documents/IETR/POSAR-MC/SW/libsbg/ui_sbgnew.h $(INSTALL_ROOT)/usr/include/qt5/ietr/

uninstall_headersDataFiles: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/include/qt5/ietr/ui_sbgnew.h
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/include/qt5/ietr/ui_newsbg.h
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/include/qt5/ietr/sbgreadfile.h
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/include/qt5/ietr/sbgnew.h
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/include/qt5/ietr/sbgecomlogstatus.h
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/include/qt5/ietr/sbgecomlogdata.h
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/include/qt5/ietr/sbgconnection.h
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/include/qt5/ietr/qwsbg.h
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/include/qt5/ietr/libsbg_global.h
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/include/qt5/ietr/libsbg.h
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/include/qt5/ietr/ 


install_libraryFiles: first FORCE
	@test -d $(INSTALL_ROOT)/usr/lib64 || mkdir -p $(INSTALL_ROOT)/usr/lib64
	-$(INSTALL_PROGRAM) /home/pleroy/Documents/IETR/POSAR-MC/SW/libsbg/liblibsbg.so $(INSTALL_ROOT)/usr/lib64/
	-$(INSTALL_PROGRAM) /home/pleroy/Documents/IETR/POSAR-MC/SW/libsbg/liblibsbg.so.1 $(INSTALL_ROOT)/usr/lib64/
	-$(INSTALL_PROGRAM) /home/pleroy/Documents/IETR/POSAR-MC/SW/libsbg/liblibsbg.so.1.0 $(INSTALL_ROOT)/usr/lib64/
	-$(INSTALL_PROGRAM) /home/pleroy/Documents/IETR/POSAR-MC/SW/libsbg/liblibsbg.so.1.0.0 $(INSTALL_ROOT)/usr/lib64/

uninstall_libraryFiles: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib64/liblibsbg.so.1.0.0
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib64/liblibsbg.so.1.0
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib64/liblibsbg.so.1
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib64/liblibsbg.so
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/lib64/ 


install: install_target install_headersDataFiles install_libraryFiles  FORCE

uninstall: uninstall_target uninstall_headersDataFiles uninstall_libraryFiles  FORCE

FORCE:

